# Generated by Django 5.1.1 on 2024-09-17 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_group_students_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
